apiVersion: v1
kind: ConfigMap
metadata:
  name: cors-config
  labels:
    app: nanopore-microservices
    component: cors-config
data:
  CORS_ORIGINS: "https://nanopore-frontend-microservice-dept-barc.apps.cloudapps.unc.edu,https://nanopore-frontend-final-dept-barc.apps.cloudapps.unc.edu,https://nanopore-tracking-route-dept-barc.apps.cloudapps.unc.edu,http://localhost:3000,http://localhost:3001"
  CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
  CORS_HEADERS: "Content-Type,Authorization,X-Requested-With,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers"
  CORS_CREDENTIALS: "true"
  CORS_MAX_AGE: "86400" 