---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: python-gateway
  namespace: dept-barc
  labels:
    app: python-gateway
spec:
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: python-gateway:latest
  triggers:
  - type: ConfigChange

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: python-gateway
  namespace: dept-barc
  labels:
    app: python-gateway 