---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanopore-frontend
  namespace: nanopore-local
  labels:
    app: nanopore-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanopore-frontend
  template:
    metadata:
      labels:
        app: nanopore-frontend
    spec:
      containers:
      - name: nanopore-frontend
        image: nanopore-frontend:local
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: HOST
          value: "0.0.0.0"
        - name: DATABASE_URL
          value: "postgresql://nanopore_user:nanopore_pass@postgres:5432/nanopore_db"
        - name: SUBMISSION_SERVICE_URL
          value: "http://submission-service:8000"
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 15
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: nanopore-frontend
  namespace: nanopore-local
spec:
  selector:
    app: nanopore-frontend
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  type: ClusterIP 