---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanopore-frontend
  namespace: nanopore-local
  labels:
    app: nanopore-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanopore-frontend
  template:
    metadata:
      labels:
        app: nanopore-frontend
    spec:
      containers:
      - name: nanopore-frontend
        image: nanopore-frontend:local
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: HOST
          value: "0.0.0.0"
        - name: SAMPLE_MANAGEMENT_URL
          value: "http://sample-management:3002"
        - name: SUBMISSION_SERVICE_URL
          value: "http://submission-service:8000"
        - name: AUTH_SERVICE_URL
          value: "http://authentication:3003"
        - name: FILE_STORAGE_URL
          value: "http://file-storage:3004"
        - name: AUDIT_SERVICE_URL
          value: "http://audit:3005"
        - name: AI_PROCESSING_URL
          value: "http://ai-processing:3006"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: nanopore-frontend
  namespace: nanopore-local
spec:
  selector:
    app: nanopore-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP 