apiVersion: v1
kind: ConfigMap
metadata:
  name: nanopore-config
  labels:
    app: nanopore-tracking-app
data:
  ollama-host: "http://ollama-service:11434"
  submission-service-url: "http://submission-service:8000"
  app-name: "Nanopore Tracking App"
  log-level: "info"
  cors-origins: "https://nanopore-frontend-final-dept-barc.apps.cloudapps.unc.edu,https://nanopore-tracking-route-dept-barc.apps.cloudapps.unc.edu"