apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanopore-tracking-app
  labels:
    app: nanopore-tracking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanopore-tracking-app
  template:
    metadata:
      labels:
        app: nanopore-tracking-app
    spec:
      containers:
      - name: nanopore-tracking-app
        image: image-registry.openshift-image-registry.svc:5000/dept-barc/nanopore-tracking-app:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: nanopore-secrets
              key: database-url
        - name: OLLAMA_HOST
          valueFrom:
            configMapKeyRef:
              name: nanopore-config
              key: ollama-host
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: nanopore-tracking-service
  labels:
    app: nanopore-tracking-app
spec:
  selector:
    app: nanopore-tracking-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nanopore-tracking-route
  labels:
    app: nanopore-tracking-app
spec:
  to:
    kind: Service
    name: nanopore-tracking-service
  port:
    targetPort: 3001
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect