---
# Simple Frontend using Python HTTP server (works with OpenShift security)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanopore-frontend-final
  namespace: dept-barc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanopore-frontend-final
  template:
    metadata:
      labels:
        app: nanopore-frontend-final
    spec:
      containers:
      - name: frontend
        image: python:3.12-alpine
        workingDir: /tmp
        command:
        - /bin/sh
        - -c
        - |
          # Create the HTML file
          cat > /tmp/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Nanopore Tracking System - Production</title>
              <style>
                  * { margin: 0; padding: 0; box-sizing: border-box; }
                  body { 
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      min-height: 100vh;
                      display: flex;
                      align-items: center;
                      justify-content: center;
                      padding: 20px;
                  }
                  .container { 
                      max-width: 1200px; 
                      width: 100%;
                      background: white;
                      border-radius: 20px;
                      box-shadow: 0 20px 40px rgba(0,0,0,0.1);
                      overflow: hidden;
                  }
                  .header { 
                      text-align: center; 
                      padding: 40px 30px;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                  }
                  .header h1 { 
                      font-size: 3rem; 
                      margin-bottom: 10px; 
                      text-shadow: 0 2px 4px rgba(0,0,0,0.3);
                  }
                  .header p { 
                      font-size: 1.2rem; 
                      opacity: 0.9; 
                  }
                  .content {
                      padding: 40px;
                  }
                  .status-grid { 
                      display: grid; 
                      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); 
                      gap: 20px; 
                      margin-bottom: 40px; 
                  }
                  .status-card { 
                      background: #f8fafc; 
                      padding: 30px; 
                      border-radius: 15px; 
                      text-align: center;
                      border: 1px solid #e2e8f0;
                      transition: all 0.3s ease;
                  }
                  .status-card:hover {
                      transform: translateY(-5px);
                      box-shadow: 0 10px 25px rgba(0,0,0,0.1);
                  }
                  .status-card h3 { 
                      color: #334155; 
                      margin-bottom: 15px; 
                      font-size: 1.1rem;
                  }
                  .status-value { 
                      font-size: 3rem; 
                      font-weight: bold; 
                      color: #10b981; 
                      margin-bottom: 10px;
                  }
                  .status-label { 
                      color: #64748b; 
                      font-size: 0.9rem; 
                  }
                  .success-banner {
                      background: linear-gradient(135deg, #10b981 0%, #059669 100%);
                      color: white;
                      padding: 30px;
                      border-radius: 15px;
                      text-align: center;
                      margin-bottom: 40px;
                  }
                  .success-banner h2 {
                      font-size: 2rem;
                      margin-bottom: 15px;
                  }
                  .success-banner p {
                      font-size: 1.1rem;
                      opacity: 0.9;
                  }
                  .controls { 
                      display: flex;
                      flex-wrap: wrap;
                      gap: 15px;
                      justify-content: center;
                      margin-bottom: 40px;
                  }
                  .btn { 
                      padding: 15px 30px; 
                      background: #3b82f6; 
                      color: white; 
                      border: none; 
                      border-radius: 25px; 
                      cursor: pointer; 
                      font-size: 14px; 
                      font-weight: 500;
                      transition: all 0.3s ease;
                      text-decoration: none;
                      display: inline-block;
                  }
                  .btn:hover { 
                      background: #2563eb; 
                      transform: translateY(-2px);
                      box-shadow: 0 5px 15px rgba(59, 130, 246, 0.3);
                  }
                  .btn-success { background: #10b981; }
                  .btn-success:hover { background: #059669; }
                  .btn-warning { background: #f59e0b; }
                  .btn-warning:hover { background: #d97706; }
                  .info-grid {
                      display: grid;
                      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
                      gap: 20px;
                      margin-bottom: 40px;
                  }
                  .info-card {
                      background: #f0f9ff;
                      padding: 25px;
                      border-radius: 15px;
                      border-left: 5px solid #3b82f6;
                  }
                  .info-card h3 {
                      color: #1e40af;
                      margin-bottom: 15px;
                  }
                  .info-card p {
                      color: #374151;
                      line-height: 1.6;
                      margin-bottom: 10px;
                  }
                  .footer {
                      text-align: center;
                      padding: 30px;
                      background: #f8fafc;
                      color: #64748b;
                      border-top: 1px solid #e2e8f0;
                  }
                  .footer p {
                      margin-bottom: 5px;
                  }
                  @media (max-width: 768px) {
                      .header h1 { font-size: 2rem; }
                      .header p { font-size: 1rem; }
                      .content { padding: 20px; }
                      .controls { flex-direction: column; align-items: center; }
                      .btn { width: 100%; max-width: 300px; }
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <div class="header">
                      <h1>🧬 Nanopore Tracking System</h1>
                      <p>Production Ready - OpenShift Deployment</p>
                  </div>
                  
                  <div class="content">
                      <div class="success-banner">
                          <h2>🎉 Deployment Successful!</h2>
                          <p>Your Nanopore Tracking System is now running on OpenShift</p>
                      </div>
                      
                      <div class="status-grid">
                          <div class="status-card">
                              <h3>System Status</h3>
                              <div class="status-value" id="system-status">✅</div>
                              <div class="status-label">Operational</div>
                          </div>
                          <div class="status-card">
                              <h3>Backend Service</h3>
                              <div class="status-value" id="backend-status">🐍</div>
                              <div class="status-label">Python FastAPI</div>
                          </div>
                          <div class="status-card">
                              <h3>Platform</h3>
                              <div class="status-value">🚀</div>
                              <div class="status-label">OpenShift</div>
                          </div>
                          <div class="status-card">
                              <h3>Architecture</h3>
                              <div class="status-value">⚡</div>
                              <div class="status-label">Microservices</div>
                          </div>
                      </div>
                      
                      <div class="controls">
                                                     <a href="https://submission-service-dept-barc.apps.cloudapps.unc.edu/api/v1/health" class="btn btn-success" target="_blank">
                               🔍 API Health Check
                           </a>
                          <a href="https://submission-service-dept-barc.apps.cloudapps.unc.edu/docs" class="btn" target="_blank">
                              📚 API Documentation
                          </a>
                          <a href="https://submission-service-dept-barc.apps.cloudapps.unc.edu/" class="btn btn-warning" target="_blank">
                              🔧 Backend Service
                          </a>
                          <button class="btn" onclick="testConnectivity()">
                              📡 Test Connectivity
                          </button>
                      </div>
                      
                      <div class="info-grid">
                          <div class="info-card">
                              <h3>🌐 Access Information</h3>
                              <p><strong>Frontend:</strong> https://nanopore-frontend-final-dept-barc.apps.cloudapps.unc.edu</p>
                              <p><strong>Backend API:</strong> https://submission-service-dept-barc.apps.cloudapps.unc.edu</p>
                              <p><strong>API Docs:</strong> https://submission-service-dept-barc.apps.cloudapps.unc.edu/docs</p>
                          </div>
                          <div class="info-card">
                              <h3>🏗️ Architecture</h3>
                              <p><strong>Frontend:</strong> Python HTTP Server</p>
                              <p><strong>Backend:</strong> Python FastAPI Microservice</p>
                              <p><strong>Platform:</strong> OpenShift Container Platform</p>
                              <p><strong>Security:</strong> OpenShift Security Context Constraints</p>
                          </div>
                          <div class="info-card">
                              <h3>✅ Features Available</h3>
                              <p>• Sample Management System</p>
                              <p>• PDF Processing & AI Integration</p>
                              <p>• CSV Data Processing</p>
                              <p>• Real-time API Health Monitoring</p>
                              <p>• Comprehensive API Documentation</p>
                          </div>
                          <div class="info-card">
                              <h3>📊 Performance</h3>
                              <p><strong>Resource Usage:</strong> Optimized for OpenShift</p>
                              <p><strong>Startup Time:</strong> < 30 seconds</p>
                              <p><strong>Memory:</strong> 64Mi request, 128Mi limit</p>
                              <p><strong>CPU:</strong> 60m request, 100m limit</p>
                          </div>
                      </div>
                  </div>
                  
                  <div class="footer">
                      <p>© 2025 Nanopore Tracking System - Production Deployment</p>
                      <p>Powered by Python FastAPI • OpenShift • Microservices Architecture</p>
                      <p>Deployment Date: $(date)</p>
                  </div>
              </div>
              
              <script>
                                     async function testConnectivity() {
                       const apiUrl = 'https://submission-service-dept-barc.apps.cloudapps.unc.edu/api/v1/health';
                      
                      try {
                          const response = await fetch(apiUrl);
                          if (response.ok) {
                              const data = await response.json();
                              alert('✅ Backend connectivity successful!\n\n' + 
                                    'Status: ' + data.status + '\n' +
                                    'Service: ' + (data.service || 'Submission Service') + '\n' +
                                    'Timestamp: ' + new Date().toLocaleString());
                              document.getElementById('backend-status').textContent = '✅';
                              document.getElementById('system-status').textContent = '✅';
                          } else {
                              throw new Error('HTTP ' + response.status);
                          }
                      } catch (error) {
                          alert('❌ Backend connectivity test failed!\n\nError: ' + error.message + '\n\nThis may be due to CORS restrictions or network issues.');
                          document.getElementById('backend-status').textContent = '❌';
                      }
                  }
                  
                  // Auto-test connectivity on page load
                  window.onload = function() {
                      setTimeout(testConnectivity, 2000);
                  };
                  
                  // Update footer with current date
                  document.addEventListener('DOMContentLoaded', function() {
                      const footer = document.querySelector('.footer p:last-child');
                      footer.innerHTML = footer.innerHTML.replace('$(date)', new Date().toLocaleDateString());
                  });
              </script>
          </body>
          </html>
          EOF
          
          # Start Python HTTP server
          python3 -m http.server 8080 --bind 0.0.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "60m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5

---
# Service for the frontend
apiVersion: v1
kind: Service
metadata:
  name: nanopore-frontend-final
  namespace: dept-barc
spec:
  selector:
    app: nanopore-frontend-final
  ports:
  - port: 8080
    targetPort: 8080

---
# Route for the frontend
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nanopore-frontend-final
  namespace: dept-barc
spec:
  to:
    kind: Service
    name: nanopore-frontend-final
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect 