---
# Simple Frontend that connects to existing submission service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanopore-frontend-simple
  namespace: dept-barc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanopore-frontend-simple
  template:
    metadata:
      labels:
        app: nanopore-frontend-simple
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "60m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: html-content
        configMap:
          name: frontend-html

---
# ConfigMap with HTML content
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
  namespace: dept-barc
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Nanopore Tracking - Production System</title>
        <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { 
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
            }
            .container { 
                max-width: 1200px; 
                margin: 0 auto; 
                padding: 20px; 
                background: white;
                border-radius: 20px;
                box-shadow: 0 20px 40px rgba(0,0,0,0.1);
            }
            .header { 
                text-align: center; 
                margin-bottom: 40px; 
                padding: 30px;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                border-radius: 15px;
            }
            .header h1 { 
                font-size: 3rem; 
                margin-bottom: 10px; 
                text-shadow: 0 2px 4px rgba(0,0,0,0.3);
            }
            .header p { 
                font-size: 1.2rem; 
                opacity: 0.9; 
            }
            .status-grid { 
                display: grid; 
                grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); 
                gap: 20px; 
                margin-bottom: 30px; 
            }
            .status-card { 
                background: #f8fafc; 
                padding: 25px; 
                border-radius: 15px; 
                text-align: center;
                border: 1px solid #e2e8f0;
                transition: all 0.3s ease;
            }
            .status-card:hover {
                transform: translateY(-5px);
                box-shadow: 0 10px 25px rgba(0,0,0,0.1);
            }
            .status-card h3 { 
                color: #334155; 
                margin-bottom: 15px; 
                font-size: 1.1rem;
            }
            .status-value { 
                font-size: 2.5rem; 
                font-weight: bold; 
                color: #10b981; 
                margin-bottom: 5px;
            }
            .status-label { 
                color: #64748b; 
                font-size: 0.9rem; 
            }
            .controls { 
                background: #f8fafc; 
                padding: 25px; 
                border-radius: 15px; 
                margin-bottom: 30px; 
                text-align: center;
            }
            .btn { 
                padding: 12px 30px; 
                background: #3b82f6; 
                color: white; 
                border: none; 
                border-radius: 25px; 
                cursor: pointer; 
                margin: 8px; 
                font-size: 14px; 
                font-weight: 500;
                transition: all 0.3s ease;
                text-decoration: none;
                display: inline-block;
            }
            .btn:hover { 
                background: #2563eb; 
                transform: translateY(-2px);
                box-shadow: 0 5px 15px rgba(59, 130, 246, 0.3);
            }
            .btn-success { background: #10b981; }
            .btn-success:hover { background: #059669; }
            .btn-warning { background: #f59e0b; }
            .btn-warning:hover { background: #d97706; }
            .info-section {
                background: #f0f9ff;
                padding: 25px;
                border-radius: 15px;
                border-left: 5px solid #3b82f6;
                margin-bottom: 20px;
            }
            .info-section h3 {
                color: #1e40af;
                margin-bottom: 15px;
            }
            .info-section p {
                color: #374151;
                line-height: 1.6;
                margin-bottom: 10px;
            }
            .feature-grid {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
                gap: 20px;
                margin-top: 30px;
            }
            .feature-card {
                background: white;
                padding: 20px;
                border-radius: 10px;
                border: 1px solid #e2e8f0;
                text-align: center;
            }
            .feature-icon {
                font-size: 2.5rem;
                margin-bottom: 15px;
            }
            .footer {
                text-align: center;
                margin-top: 40px;
                padding: 20px;
                color: #64748b;
                border-top: 1px solid #e2e8f0;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🧬 Nanopore Tracking System</h1>
                <p>Production Ready - OpenShift Deployment</p>
            </div>
            
            <div class="status-grid">
                <div class="status-card">
                    <h3>System Status</h3>
                    <div class="status-value" id="system-status">✅</div>
                    <div class="status-label">Operational</div>
                </div>
                <div class="status-card">
                    <h3>Backend Service</h3>
                    <div class="status-value" id="backend-status">🐍</div>
                    <div class="status-label">Python FastAPI</div>
                </div>
                <div class="status-card">
                    <h3>Environment</h3>
                    <div class="status-value">🚀</div>
                    <div class="status-label">OpenShift</div>
                </div>
                <div class="status-card">
                    <h3>Architecture</h3>
                    <div class="status-value">⚡</div>
                    <div class="status-label">Microservices</div>
                </div>
            </div>
            
            <div class="controls">
                <a href="https://submission-service-dept-barc.apps.cloudapps.unc.edu/health" class="btn btn-success" target="_blank">
                    🔍 API Health Check
                </a>
                <a href="https://submission-service-dept-barc.apps.cloudapps.unc.edu/docs" class="btn" target="_blank">
                    📚 API Documentation
                </a>
                <a href="https://submission-service-dept-barc.apps.cloudapps.unc.edu/" class="btn btn-warning" target="_blank">
                    🔧 Backend Service
                </a>
                <button class="btn" onclick="testConnectivity()">
                    📡 Test Connectivity
                </button>
            </div>
            
            <div class="info-section">
                <h3>🎉 Deployment Successful!</h3>
                <p><strong>Frontend URL:</strong> https://nanopore-frontend-dept-barc.apps.cloudapps.unc.edu</p>
                <p><strong>Backend API:</strong> https://submission-service-dept-barc.apps.cloudapps.unc.edu</p>
                <p><strong>Architecture:</strong> Python FastAPI microservices with Nginx frontend</p>
                <p><strong>Platform:</strong> OpenShift Container Platform</p>
            </div>
            
            <div class="feature-grid">
                <div class="feature-card">
                    <div class="feature-icon">🧬</div>
                    <h3>Sample Management</h3>
                    <p>Complete CRUD operations for nanopore samples with status tracking and priority management.</p>
                </div>
                <div class="feature-card">
                    <div class="feature-icon">📊</div>
                    <p>Real-time monitoring and analytics dashboard with comprehensive reporting capabilities.</p>
                </div>
                <div class="feature-card">
                    <div class="feature-icon">🔒</div>
                    <h3>Security</h3>
                    <p>Enterprise-grade security with authentication, authorization, and audit logging.</p>
                </div>
                <div class="feature-card">
                    <div class="feature-icon">⚡</div>
                    <h3>Performance</h3>
                    <p>High-performance Python FastAPI backend with optimized database queries and caching.</p>
                </div>
            </div>
            
            <div class="footer">
                <p>© 2025 Nanopore Tracking System - Production Deployment</p>
                <p>Powered by Python FastAPI • OpenShift • Microservices Architecture</p>
            </div>
        </div>
        
        <script>
            async function testConnectivity() {
                const apiUrl = 'https://submission-service-dept-barc.apps.cloudapps.unc.edu/health';
                
                try {
                    const response = await fetch(apiUrl);
                    if (response.ok) {
                        const data = await response.json();
                        alert('✅ Backend connectivity successful!\n\n' + 
                              'Status: ' + data.status + '\n' +
                              'Service: ' + (data.service || 'Submission Service') + '\n' +
                              'Response time: ' + response.headers.get('date'));
                        document.getElementById('backend-status').textContent = '✅';
                    } else {
                        throw new Error('HTTP ' + response.status);
                    }
                } catch (error) {
                    alert('❌ Backend connectivity failed!\n\nError: ' + error.message);
                    document.getElementById('backend-status').textContent = '❌';
                }
            }
            
            // Auto-test connectivity on page load
            window.onload = function() {
                setTimeout(testConnectivity, 2000);
            };
        </script>
    </body>
    </html>

---
# Service for the frontend
apiVersion: v1
kind: Service
metadata:
  name: nanopore-frontend-simple
  namespace: dept-barc
spec:
  selector:
    app: nanopore-frontend-simple
  ports:
  - port: 80
    targetPort: 80

---
# Route for the frontend
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nanopore-frontend
  namespace: dept-barc
spec:
  to:
    kind: Service
    name: nanopore-frontend-simple
  port:
    targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect 