apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nanopore-frontend
  labels:
    app: nanopore-frontend
    service: frontend
spec:
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: nanopore-frontend:latest
  triggers:
  - type: ConfigChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nanopore-frontend
  labels:
    app: nanopore-frontend
    service: frontend 