global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # API Gateway metrics
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3001']
    metrics_path: '/metrics/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Sample Management Service metrics
  - job_name: 'sample-management'
    static_configs:
      - targets: ['sample-management:3002']
    metrics_path: '/metrics/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s

  # AI Processing Service metrics
  - job_name: 'ai-processing'
    static_configs:
      - targets: ['ai-processing:3003']
    metrics_path: '/metrics/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Authentication Service metrics
  - job_name: 'authentication'
    static_configs:
      - targets: ['authentication:3004']
    metrics_path: '/metrics/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s

  # File Storage Service metrics
  - job_name: 'file-storage'
    static_configs:
      - targets: ['file-storage:3005']
    metrics_path: '/metrics/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Audit Service metrics
  - job_name: 'audit'
    static_configs:
      - targets: ['audit:3006']
    metrics_path: '/metrics/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Submission Service metrics (Python FastAPI)
  - job_name: 'submission-service'
    static_configs:
      - targets: ['submission-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Frontend Service metrics
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3007']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Database metrics
  - job_name: 'postgres-sample'
    static_configs:
      - targets: ['sample-db:5432']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'postgres-ai'
    static_configs:
      - targets: ['ai-db:5432']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'postgres-auth'
    static_configs:
      - targets: ['auth-db:5432']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'postgres-file'
    static_configs:
      - targets: ['file-db:5432']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'postgres-audit'
    static_configs:
      - targets: ['audit-db:5432']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Ollama metrics
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Vector DB metrics
  - job_name: 'vector-db'
    static_configs:
      - targets: ['vector-db:6333']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    scrape_timeout: 10s