apiVersion: apps/v1
kind: Deployment
metadata:
  name: submission-service
  labels:
    app: submission-service
    service: submission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: submission-service
  template:
    metadata:
      labels:
        app: submission-service
        service: submission
    spec:
      containers:
      - name: submission-service
        image: submission-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: MAIN_APP_URL
          value: "http://nanopore-tracking-app:3001"
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        - name: PORT
          value: "8000"
        - name: HOST
          value: "0.0.0.0"
        - name: CORS_ORIGINS
          value: "https://nanopore-frontend-final-dept-barc.apps.cloudapps.unc.edu,https://nanopore-tracking-route-dept-barc.apps.cloudapps.unc.edu"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        - name: PYTHONOPTIMIZE
          value: "1"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: temp-storage
          mountPath: /tmp
      volumes:
      - name: temp-storage
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: submission-service
  labels:
    app: submission-service
    service: submission
spec:
  selector:
    app: submission-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: submission-service-route
  labels:
    app: submission-service
    service: submission
spec:
  host: submission-service-dept-barc.apps.cloudapps.unc.edu
  to:
    kind: Service
    name: submission-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect 